name: content-model
inputs:
  INPUT:
    required: true
  OUTPUT:
    required: true
  DIR:
    required: true
  SCHEMAS:
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    - name: Generate content models
      shell: bash
      run: |
        gradle \
          -Pinput="../${{ inputs.INPUT }}" \
          -Poutput="../${{ inputs.DIR }}/${{ inputs.OUTPUT }}" \
          -Pschemas="${{ inputs.SCHEMAS }}"
      working-directory: dita-lang
    - name: Insert content models
      shell: bash
      run: |
        for i in *.dita; do
          echo "$i"
          name=${i%%.*}
          perl -p -e "s/(<section(?:\s+[\w-]+=[\"'].+?[\"'])*(\s+id=\"attributes\")(?:\s+[\w-]+=[\"'].+?[\"'])*+\s*\/?>)/<section conref=\"${{ inputs.OUTPUT }}#content-models\/${name}.element\" id=\"content-model\"\/>\1/" "$i" > "$i.bak"
          mv "$i.bak" "$i"
        done
      working-directory: ${{ inputs.DIR }}
