name: content-model
inputs:
  INPUT:
    required: true
  OUTPUT:
    required: true
  DIR:
    required: true
  MAP:
    required: true
  PREFIX:
    required: false
    default: ''
  SCHEMAS:
    required: true
  VERSION:
    required: false
    default: '2'
runs:
  using: 'composite'
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version-file: ${{ github.action_path }}/.python-version
    - name: Generate content models
      shell: bash
      run: |
        elementSuffix=".element"
        elementPrefix="${{ inputs.PREFIX }}"
        for schema in $(echo "${{ inputs.SCHEMAS }}" | tr ':' '\n'); do
          #dir="$(dirname ${schema})"
          file="$(basename ${schema})"
          gradle \
            -Pinput="../${{ inputs.INPUT }}/${schema}" \
            -Poutput="../${{ inputs.DIR }}/${file%%.rng}.dita" \
            -Pschema="${file}" \
            -Pelement-suffix="${elementSuffix}" \
            -Pelement-prefix="${elementPrefix}"
        done
        echo "Generated:"
        ls ../${{ inputs.DIR }}
      working-directory: dita-lang
    - name: Insert content models
      shell: bash
      run: |
        # Insert to topics
        #for output in $(echo "${{ inputs.OUTPUT }}" | tr ':' '\n'); do
        output=${{ inputs.OUTPUT }}
        dir=$(basename ${output})
        cd $output
        for i in *.dita; do
          name=${i%%.*}
          name=${name##${{ inputs.PREFIX }}}
          echo "$i $name"
          # XXX This may not be needed anymore
          #perl -pi.bak -e 's/<!--(<section id="attributes"><title>Attributes<\/title><p conkeyref="reuse-attributes\/no-atts"\/><\/section>)-->/\1/g' "$i"
          #rm "$i.bak"
          if [[ "${{ inputs.VERSION }}" == "2" ]]; then
            python "${{ github.action_path }}/replace_by_attr.py" "$i" "attributes" prepend "<section conkeyref=\"content-models-${name}/${name}.element\" id=\"content-model\"/><section conkeyref=\"inheritance-${name}/${name}.inheritance\" id=\"inheritance\"/>"
          else
            python "${{ github.action_path }}/replace_by_attr.py" "$i" "contains" replace "<section conkeyref=\"content-models-${name}/${name}.element\" id=\"content-model\"/>"
            python "${{ github.action_path }}/replace_by_attr.py" "$i" "inheritance" replace "<section conkeyref=\"inheritance-${name}/${name}.inheritance\" id=\"inheritance\"/>"
          fi
        done
        cd -
        #done
        # Insert to map
        for schema in $(echo "${{ inputs.SCHEMAS }}" | tr ':' '\n'); do
          file="$(basename ${schema})"
          name=${file%%.rng}
          perl -pi.bak -e "s/(<\/map>)/  <mapref href='content-models\/${name}.ditamap'\/>\n\1/" "${{ inputs.MAP }}"
          rm "${{ inputs.MAP }}.bak"
        done
        #git status
        #git diff -- "${{ inputs.MAP }}"
      #working-directory: ${{ inputs.OUTPUT }}
