name: publish
inputs:
  MAP:
    required: true
  FILTER:
    required: true
  DIR:
    required: true
  REPOSITORY:
    required: true
runs:
  using: 'composite'
  steps:
    - name: Get source commit
      shell: bash
      run: |
        echo "SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
      working-directory: ${{ inputs.DIR }}
    - name: Add custom filter
      shell: bash
      run: |
        cat <<EOF > ${{ inputs.FILTER }}.external-publishing-engine.ditaval
        <val>
          <prop att="platform" val="dita-tc-publishing" action="exclude"/>
          <prop att="platform" val="external-publishing-engine" action="include"/>
        </val>
        EOF
    - name: Run single page DITA-OT
      if: ${{ false }}
      shell: bash
      run: |
        $DITA_HOME/bin/dita \
          -i ${{ inputs.MAP }} \
          -o dita-lang/${{ inputs.DIR }} \
          -f org.dita-ot.html \
          --filter=${{ inputs.FILTER }}.external-publishing-engine.ditaval \
          --filter=${{ inputs.FILTER }} \
          -Dcommit=$SHA \
          -Drepository=${{ inputs.REPOSITORY }} \
          --root-chunk-override=to-content \
          -Dnav-toc=full -v
    - name: Run multi-page DITA-OT
      shell: bash
      run: |
        $DITA_HOME/bin/dita \
          -i ${{ inputs.MAP }} \
          -o dita-lang/${{ inputs.DIR }} \
          -f org.dita-ot.html \
          --filter=${{ inputs.FILTER }}.external-publishing-engine.ditaval \
          --filter=${{ inputs.FILTER }} \
          -Dcommit=$SHA \
          -Drepository=${{ inputs.REPOSITORY }}
    - name: Reset unchanged
      shell: bash
      run: |
        git diff --name-only | while read i; do
          echo $i
          diff="$(git diff -U0 "$i")"
          echo $diff
          lines="$(echo $diff | wc -l)"
          if [ $lines -eq 7 ]; then
            if [ "$(echo $diff | sed -n '6p')" =~ '^-commit:*' ] && [ "$(echo $diff | sed -n '7p')" =~ '^\+commit:*' ]; then
              git checkout -- "$i"
            fi
          fi
          echo
        done
      working-directory: dita-lang
    - name: Commit changes
      shell: bash
      run: |
        if [ $(git status -s | wc -l) != 0 ]; then
          git config user.email "ditaotbot@gmail.com"
          git config user.name "DITA-OT Bot"
          git add --all
          # Commit generated site output
          git commit -a -m "Deploy ${{ inputs.REPOSITORY }}@${SHA:0:7}"
        else
          echo "Nothing to commit"
        fi
      working-directory: dita-lang
