name: publish
inputs:
  MAP:
    required: true
  FILTER:
    required: true
  DIR:
    required: true
  OUTPUT_DIR:
    required: true
  REPOSITORY:
    required: true
runs:
  using: 'composite'
  steps:
    - name: Get source commit
      shell: bash
      run: |
        echo "SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
      working-directory: ${{ inputs.DIR }}
    - name: Add custom filter
      shell: bash
      run: |
        cat <<EOF > ${{ inputs.FILTER }}.external-publishing-engine.ditaval
        <val>
          <prop att="platform" val="dita-tc-publishing" action="exclude"/>
          <prop att="platform" val="external-publishing-engine" action="include"/>
        </val>
        EOF
    - name: Run multi-page DITA-OT
      shell: bash
      run: |
        rm -rf dita-lang/${{ inputs.OUTPUT_DIR }}/*
        $DITA_HOME/bin/dita \
          -i ${{ inputs.MAP }} \
          -o dita-lang/${{ inputs.OUTPUT_DIR }} \
          -f org.dita-ot.html \
          --filter=${{ inputs.FILTER }}.external-publishing-engine.ditaval \
          --filter=${{ inputs.FILTER }} \
          -Dcommit=$SHA \
          -Drepository=${{ inputs.REPOSITORY }}
    - name: Run single page DITA-OT
      if: ${{ true }}
      shell: bash
      run: |
        rm -rf dita-lang/${{ inputs.OUTPUT_DIR }}/single/*
        mkdir -p dita-lang/${{ inputs.OUTPUT_DIR }}/single/
        $DITA_HOME/bin/dita \
          -i ${{ inputs.MAP }} \
          -o dita-lang/${{ inputs.OUTPUT_DIR }}/single \
          -f org.dita-ot.html \
          --filter=${{ inputs.FILTER }}.external-publishing-engine.ditaval \
          --filter=${{ inputs.FILTER }} \
          -Dcommit=$SHA \
          -Drepository=${{ inputs.REPOSITORY }} \
          --root-chunk-override=to-content \
          -Dnav-toc=full -v
    - name: Reset unchanged
      shell: bash
      run: |
        changed="$(git diff --name-only)"
        echo "$changed" | while read i; do
          if [[ -e "$i" ]]; then
            lines="$(git diff --no-color -U0 "$i" | wc -l)"
            if [ $lines -eq 7 ]; then
              if [[ "$(git diff --no-color -U0 "$i" | sed -n '6p' | grep -c '^-commit:')" -eq 1 ]]; then
                if [[ "$(git diff --no-color -U0 "$i" | sed -n '7p' | grep -c '^+commit:')" -eq 1 ]]; then
                  echo "Reset $i"
                  git checkout -- "$i"
                fi
              fi
            fi
          fi
        done
      working-directory: dita-lang
    - name: Commit changes
      shell: bash
      run: |
        if [ $(git status -s | wc -l) != 0 ]; then
          git config user.email "ditaotbot@gmail.com"
          git config user.name "DITA-OT Bot"
          git add --all
          # Commit generated site output
          git commit -a -m "Deploy ${{ inputs.REPOSITORY }}@${SHA:0:7}"
        else
          echo "Nothing to commit"
        fi
      working-directory: dita-lang
