name: Build all drafts
on:
  workflow_dispatch:
  schedule:
    # every day at midnight
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DITA_OT_VERSION: '4.0'
    steps:
      - uses: actions/checkout@v3
        with:
          path: dita-lang
      - name: Init
        uses: ./dita-lang/.github/actions/init

      - uses: actions/checkout@v3
        with:
          repository: 'oasis-tcs/dita'
          ref: 'DITA-2.0'
          path: dita
      - name: Generate content models
        uses: ./dita-lang/.github/actions/content-model
        with:
          INPUT: dita/doctypes/rng/base
          OUTPUT: content-models.dita
          DIR: dita/specification/langRef/content-models
          MAP: ../base-elements.ditamap
          SCHEMAS: 'basetopic.rng:basemap.rng:subjectScheme.rng'
      - name: Publish DITA
        uses: ./dita-lang/.github/actions/publish
        with:
          MAP: dita/specification/dita-2.0-specification.ditamap
          FILTER: dita/specification/resources/DITA2.0-spec.ditaval
          DIR: dita
          REPOSITORY: oasis-tcs/dita

      - uses: actions/checkout@v3
        with:
          repository: 'oasis-tcs/dita-techcomm'
          ref: 'DITA-2.0'
          path: dita-techcomm
          submodules: recursive
      - name: Publish DITA TC
        uses: ./dita-lang/.github/actions/publish
        with:
          MAP: dita-techcomm/specification/dita-2.0-technical-content-specification.ditamap
          FILTER: dita-techcomm/specification/resources/DITA2.0-tc-spec.ditaval
          DIR: dita-techcomm
          REPOSITORY: oasis-tcs/dita-techcomm

      - uses: actions/checkout@v3
        with:
          repository: 'oasis-tcs/dita-lwdita'
          ref: 'spec'
          path: lwdita
          submodules: recursive
      - name: Publish LwDITA
        uses: ./dita-lang/.github/actions/publish
        with:
          MAP: lwdita/Spec/lwdita.ditamap
          FILTER: lwdita/Spec/resources/lwdita.ditaval
          DIR: lwdita
          REPOSITORY: oasis-tcs/dita-lwdita

      - name: Push changes
        run: |
          git push -v origin main
        working-directory: dita-lang
