name: Build all drafts
on:
  workflow_dispatch:
  schedule:
    # every day at midnight
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DITA_OT_VERSION: '4.1'
    steps:
      - uses: actions/checkout@v4
        with:
          path: dita-lang
      - name: Init
        uses: ./dita-lang/.github/actions/init

      - uses: actions/checkout@v4
        with:
          repository: 'oasis-tcs/dita'
          ref: 'DITA-2.0'
          path: dita
          token: ${{ secrets.UPLOAD_GITHUB_TOKEN }}
      - name: Generate content models
        uses: ./dita-lang/.github/actions/content-model
        with:
          INPUT: dita/doctypes/rng
          OUTPUT: dita/specification/langRef/base
          DIR: dita/specification/langRef/content-models
          MAP: dita/specification/langRef/base-elements.ditamap
          SCHEMAS: 'base/basetopic.rng:base/basemap.rng:subjectScheme/subjectScheme.rng'
      - name: Generate content models
        uses: ./dita-lang/.github/actions/content-model
        with:
          INPUT: dita/doctypes/rng
          OUTPUT: dita/specification/langRef/ditaval
          DIR: dita/specification/langRef/content-models
          MAP: dita/specification/langRef/base-elements.ditamap
          SCHEMAS: 'ditaval/ditaval.rng'

      - name: Push source changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://github.com/dita-lang/dita.git
          git fetch

          git add --all
          git commit -m "Generate content models"
          git push -v --force-with-lease origin DITA-2.0:DITA-2.0-generated
        working-directory: dita

      - name: Publish DITA
        uses: ./dita-lang/.github/actions/publish
        with:
          MAP: dita/specification/dita-2.0-specification.ditamap
          FILTER: dita/specification/resources/DITA2.0-spec.ditaval
          DIR: dita
          OUTPUT_DIR: dita
          REPOSITORY: oasis-tcs/dita

      - uses: actions/checkout@v4
        with:
          repository: 'oasis-tcs/dita-techcomm'
          ref: 'DITA-2.0'
          path: dita-techcomm
          submodules: recursive
          token: ${{ secrets.UPLOAD_GITHUB_TOKEN }}
      - name: Generate content models
        uses: ./dita-lang/.github/actions/content-model
        with:
          INPUT: dita-techcomm/doctypes/rng
          OUTPUT: dita-techcomm/specification/langRef/technicalContent
          DIR: dita-techcomm/specification/langRef/content-models
          MAP: dita-techcomm/specification/langRef/technicalContent-elements.ditamap
          SCHEMAS: 'bookmap/bookmap.rng'

      - name: Push source changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://github.com/dita-lang/dita-techcomm.git
          git fetch

          git add --all
          git commit -m "Generate content models"
          git push -v --force-with-lease origin DITA-2.0:DITA-2.0-generated
        working-directory: dita-techcomm

      - name: Publish DITA TC
        uses: ./dita-lang/.github/actions/publish
        with:
          MAP: dita-techcomm/specification/dita-2.0-technical-content-specification.ditamap
          FILTER: dita-techcomm/specification/resources/DITA2.0-tc-spec.ditaval
          DIR: dita-techcomm
          OUTPUT_DIR: dita-techcomm
          REPOSITORY: oasis-tcs/dita-techcomm

      - uses: actions/checkout@v4
        with:
          repository: 'oasis-tcs/dita-lwdita'
          ref: 'spec'
          path: lwdita
          submodules: recursive
      - name: Publish LwDITA
        uses: ./dita-lang/.github/actions/publish
        with:
          MAP: lwdita/Spec/lwdita.ditamap
          FILTER: lwdita/Spec/resources/lwdita.ditaval
          DIR: lwdita
          OUTPUT_DIR: lwdita
          REPOSITORY: oasis-tcs/dita-lwdita

      - name: Push changes
        run: |
          git push -v origin main
        working-directory: dita-lang
