name: Build DITA TC
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DITA_OT_VERSION: '4.1'
    steps:
      - uses: actions/checkout@v3
        with:
          path: dita-lang
      - name: Init
        uses: ./dita-lang/.github/actions/init
      - uses: actions/checkout@v3
        with:
          repository: 'oasis-tcs/dita-techcomm'
          ref: 'DITA-2.0'
          path: dita-techcomm
          submodules: recursive

      - uses: actions/checkout@v3
        with:
          repository: 'oasis-tcs/dita'
          ref: 'DITA-2.0'
          path: dita
      - name: Generate content models
        uses: ./dita-lang/.github/actions/content-model
        with:
          INPUT: dita-techcomm/doctypes/rng
          OUTPUT: dita-techcomm/specification/langRef/technicalContent
          DIR: dita-techcomm/specification/langRef/content-models
          MAP: dita-techcomm/specification/langRef/technicalContent-elements.ditamap
          SCHEMAS: 'bookmap/bookmap.rng'

      - name: Publish DITA TC
        uses: ./dita-lang/.github/actions/publish
        with:
          MAP: dita-techcomm/specification/dita-2.0-technical-content-specification.ditamap
          FILTER: dita-techcomm/specification/resources/DITA2.0-tc-spec.ditaval
          DIR: dita-techcomm
          REPOSITORY: oasis-tcs/dita-techcomm
      - name: Push changes
        run: |
          git push -v origin main
        working-directory: dita-lang
