name: Build DITA 1.3
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DITA_OT_VERSION: '4.4'
    steps:
      - uses: actions/checkout@v6
        with:
          path: dita-lang
      - name: Init
        uses: ./dita-lang/.github/actions/init

      - uses: actions/checkout@v6
        with:
          repository: 'oasis-tcs/dita'
          ref: 'hotfix/DITA-1.3_Errata03'
          path: dita
          token: ${{ secrets.UPLOAD_GITHUB_TOKEN }}
      - name: Generate content models
        uses: ./dita-lang/.github/actions/content-model
        with:
          INPUT: dita/doctypes/rng
          OUTPUT: dita/specification/langRef/base
          DIR: dita/specification/langRef/content-models
          MAP: dita/specification/langRef/base-elements.ditamap
          SCHEMAS: 'base/rng/basetopic.rng:base/rng/basemap.rng:subjectScheme/rng/subjectScheme.rng'
      - name: Generate content models
        uses: ./dita-lang/.github/actions/content-model
        with:
          INPUT: dita/doctypes/rng
          OUTPUT: dita/specification/langRef/ditaval
          DIR: dita/specification/langRef/content-models
          MAP: dita/specification/langRef/base-elements.ditamap
          SCHEMAS: 'ditaval/rng/ditaval.rng'
      - name: Generate content models
        uses: ./dita-lang/.github/actions/content-model
        with:
          INPUT: dita/doctypes/rng
          OUTPUT: dita/specification/langRef/technicalContent
          DIR: dita/specification/langRef/content-models
          MAP: dita/specification/langRef/technicalContent-elements.ditamap
          SCHEMAS: 'bookmap/rng/bookmap.rng:technicalContent/rng/concept.rng:technicalContent/rng/task.rng:technicalContent/rng/reference.rng:technicalContent/rng/troubleshooting.rng:technicalContent/rng/glossgroup.rng'
      - name: Generate content models
        uses: ./dita-lang/.github/actions/content-model
        with:
          INPUT: dita/doctypes/rng
          OUTPUT: dita/specification/langRef/learningTraining
          DIR: dita/specification/langRef/content-models
          MAP: dita/specification/langRef/learningTraining-elements.ditamap
          SCHEMAS: 'learning/rng/learningAssessment.rng:learning/rng/learningBookmap.rng:learning/rng/learningContent.rng:learning/rng/learningGroupMap.rng:learning/rng/learningMap.rng:learning/rng/learningObjectMap.rng:learning/rng/learningOverview.rng:learning/rng/learningPlan.rng:learning/rng/learningSummary.rng'

      - name: Push source changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          #git config user.name github-actions
          #git config user.email github-actions@github.com
          git remote set-url origin https://github.com/dita-lang/dita.git
          git fetch

          git add --all
          git commit -m "Generate content models"
          git push -v --force-with-lease origin hotfix/DITA-1.3_Errata03:hotfix/DITA-1.3_Errata03-generated
        working-directory: dita

      - name: Publish DITA
        uses: ./dita-lang/.github/actions/publish
        with:
          MAP: dita/specification/dita-1.3-errata-specification-learningTraining.ditamap
          FILTER: dita/specification/resources/DITA1.3-spec-learningTraining.ditaval
          DIR: dita
          OUTPUT_DIR: 1.3/dita
          REPOSITORY: oasis-tcs/dita

      - name: Push changes
        run: |
          git push -v origin main
        working-directory: dita-lang
