name: Build DITA TC
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DITA_OT_VERSION: '4.0'
    steps:
      - uses: actions/checkout@v3
        with:
          path: dita-draft-website
      - name: Init
        uses: ./dita-draft-website/.github/actions/init
      - uses: actions/checkout@v3
        with:
          repository: 'oasis-tcs/dita-techcomm'
          ref: 'DITA-2.0'
          path: dita-techcomm
          submodules: recursive
      - name: Publish DITA TC
        uses: ./dita-draft-website/.github/actions/publish
        with:
          MAP: dita-techcomm/specification/dita-2.0-technical-content-specification.ditamap
          FILTER: dita-techcomm/specification/resources/DITA2.0-tc-spec.ditaval
          DIR: dita-techcomm
          REPOSITORY: oasis-tcs/dita-techcomm
      - name: Push changes
        run: |
          git push -v origin main
        working-directory: dita-draft-website
