name: Build DITA
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DITA_OT_VERSION: '4.1'
    steps:
      - uses: actions/checkout@v3
        with:
          path: dita-lang
      - name: Init
        uses: ./dita-lang/.github/actions/init

      - uses: actions/checkout@v3
        with:
          repository: 'oasis-tcs/dita'
          ref: 'DITA-2.0'
          path: dita
      - name: Generate content models
        uses: ./dita-lang/.github/actions/content-model
        with:
          INPUT: dita/doctypes/rng
          OUTPUT: dita/specification/langRef/base
          DIR: dita/specification/langRef/content-models
          MAP: dita/specification/langRef/base-elements.ditamap
          SCHEMAS: 'base/basetopic.rng:base/basemap.rng:subjectScheme/subjectScheme.rng'
      - name: Generate content models
        uses: ./dita-lang/.github/actions/content-model
        with:
          INPUT: dita/doctypes/rng
          OUTPUT: dita/specification/langRef/ditaval
          DIR: dita/specification/langRef/content-models
          MAP: dita/specification/langRef/base-elements.ditamap
          SCHEMAS: 'ditaval/ditaval.rng'

      - name: Push source changes
        run: |
          git config user.email "jarno@elovirta.com"
          git config user.name "Jarno Elovirta"
          git remote add fork https://${{ secrets.UPLOAD_GITHUB_TOKEN }}@github.com/jelovirt/dita.git
          git remote -v
          git add --all
          git push -v --force-with-lease fork DITA-2.0:DITA-2.0-generated
        working-directory: dita

      - name: Publish DITA
        uses: ./dita-lang/.github/actions/publish
        with:
          MAP: dita/specification/dita-2.0-specification.ditamap
          FILTER: dita/specification/resources/DITA2.0-spec.ditaval
          DIR: dita
          REPOSITORY: oasis-tcs/dita

      - name: Push changes
        run: |
          git push -v origin main
        working-directory: dita-lang
