name: Build LwDITA
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DITA_OT_VERSION: '4.1'
    steps:
      - uses: actions/checkout@v4
        with:
          path: dita-lang
      - name: Init
        uses: ./dita-lang/.github/actions/init
      - uses: actions/checkout@v4
        with:
          repository: 'oasis-tcs/dita-lwdita'
          ref: 'spec'
          path: lwdita
          submodules: recursive
      - name: Publish LwDITA
        uses: ./dita-lang/.github/actions/publish
        with:
          MAP: lwdita/Spec/lwdita.ditamap
          FILTER: lwdita/Spec/resources/lwdita.ditaval
          DIR: lwdita
          OUTPUT_DIR: lwdita
          REPOSITORY: oasis-tcs/dita-lwdita
      - name: Push changes
        run: |
          git push -v origin main
        working-directory: dita-lang
